### ISSUE TITLE
Fetch the response of all the tasks

### ISSUE THREAD

**Issue by amanadi007** [dexecutor/dexecutor-core#10]
how do i fetch the response of all the tasks executed after the executor.execute() is complete, i found one way in here https://github.com/dexecutor/dexecutor-core/wiki 

Collection<Node<Integer, Integer>> processedNodesOrder = TestUtil.processedNodesOrder(executor);

public static Collection<Node<Integer, Integer>> processedNodesOrder(DefaultDexecutor<Integer, Integer> executor) {
		DefaultDexecutorState<Integer, Integer> state = Deencapsulation.getField(executor, "state");
		return Deencapsulation.getField(state, "processedNodes");
	}

but it seems like this should not be the ideal way to fetch the response, can you please help me here?

**Comment by KevinOfNeu** [comment]
@amanadi007 refer to [LoggerTask](https://github.com/dexecutor/dexecutor-core/blob/1a8797078436cc2936a2ca8a562985924456ff13/src/main/java/com/github/dexecutor/core/task/LoggerTask.java#L43) which extends AbstractDelegatingTask to implement AOP like mechanism.

**Comment by mnadeem** [comment]
Thanks @KevinOfNeu

**Comment by KevinOfNeu** [comment]
Dexecutor.execute returns ExecutionResults.

**Comment by mnadeem** [comment]
@amanadi007  can this be closed ?

**Comment by mnadeem** [comment]
closing it.

**Comment by amanadi007** [comment]
@mnadeem I looked into the Dexecutor.execute method here https://github.com/dexecutor/dexecutor-core/blob/master/src/main/java/com/github/dexecutor/core/DefaultDexecutor.java#L121-L141 but it seems this method only returns the execution result of those nodes which are errored but not those which are successfully processed. 

Previously, i used the dencapsulation class provided by Jmockit to fetch the results of processed nodes similar to what has been done here in the example provided https://github.com/dexecutor/dexecutor-core/wiki

However, the dencapsulation class has been deprecated from JMockit and thus I no longer can use the above solution. Can you please provide the insights on how i can fetch the results of processed nodes?

Apologies for the late reply.
