### ISSUE TITLE
Traverser Priority 

### ISSUE THREAD

**Issue by FriedEgg** [dexecutor/dexecutor-core#12]
How do I create a traverser that considers the number of dependents and offers the node with the most outgoing edges first?

**Comment by mnadeem** [comment]
Kindly look at implementations of com.github.dexecutor.core.graph.Traversar<T, R>

**Comment by FriedEgg** [comment]
Ok, it wasn't immediately clear to me whether the Traversar affected the actual order of execution or not.  I will give this a shot.

**Comment by mnadeem** [comment]
Some examples

com.github.dexecutor.core.graph.LevelOrderTraversarTest
com.github.dexecutor.core.graph.MergedLevelOrderTraversarTest

**Comment by kumarkrish85** [comment]
@FriedEgg can you please help me with the traversar? https://github.com/dexecutor/dexecutor-core/issues/17
