### ISSUE TITLE
Fetch the result of processed nodes

### ISSUE THREAD

**Issue by amanadi007** [dexecutor/dexecutor-core#13]
This is related to this issue https://github.com/dexecutor/dexecutor-core/issues/10

@mnadeem I looked into the Dexecutor.execute method here https://github.com/dexecutor/dexecutor-core/blob/master/src/main/java/com/github/dexecutor/core/DefaultDexecutor.java#L121-L141 but it seems this method only returns the execution result of those nodes which are errored but not those which are successfully processed.

Previously, i used the dencapsulation class provided by Jmockit to fetch the results of processed nodes similar to what has been done here in the example provided https://github.com/dexecutor/dexecutor-core/wiki

However, the dencapsulation class has been deprecated from JMockit and thus I no longer can use the above solution. Can you please provide the insights on how i can fetch the results of processed nodes?

Apologies for the late reply.

**Comment by amanadi007** [comment]
@mnadeem, Hi Nadeem, can you please look into this?

**Comment by mnadeem** [comment]
Let me look into this

**Comment by amanadi007** [comment]
@mnadeem Did you get chance to look into this?

**Comment by mnadeem** [comment]
I am working on this

**Comment by mnadeem** [comment]
Meanwhile you can take help of ExecutionListener

**Comment by mnadeem** [comment]
Code has been checked in will release soon after testing

https://github.com/dexecutor/dexecutor-core/commit/7430e45ed299fe66956e39f486ee510f81d9fea3
