### ISSUE TITLE
Get the results of the nodes according to one's need.

### ISSUE THREAD

**Issue by Ruch12** [dexecutor/dexecutor-core#14]
I am working on my college project in which I have tried implementing the dexecutor's approach. After creating the dependency graph , the nodes are getting executed and I have verified this by printing the responses for every node during its execution. But at the end , when the execution is completed, if now I want a particular node's response, how will I get it? I have tried getting the response of ExecutionResults but it gives me empty response and which is logical because, execution results returns all the errored nodes. But , what is the actual preferred approach?

**Comment by Ruch12** [comment]
@mnadeem Could you please help me with this issue? Can you provide any work-around for this scenario?

**Comment by mnadeem** [comment]
I am working on this

**Comment by mnadeem** [comment]
Meanwhile you can take help of ExecutionListener

**Comment by mnadeem** [comment]
Code has been checked in will release soon after testing 

https://github.com/dexecutor/dexecutor-core/commit/7430e45ed299fe66956e39f486ee510f81d9fea3

**Comment by Ruch12** [comment]
@mnadeem By when will you release the changes? I have a deadline for my project. Could you please let me know the updates?
