### ISSUE TITLE
Run particular independent task sequentially

### ISSUE THREAD

**Issue by kumarkrish85** [dexecutor/dexecutor-core#16]
I am using this package in my automation project. Some tasks (automation test case) have IE browser mapped, as per selenium is not recommended to run the IE test cases in parallel. To avoid running it in parallel I made it sequential by marking dependency something like this. 

IE.TC1, IE.TC2

TC2 depends on TC1, So handled error scenario in should Execute method. But my requirement is to run them as independent tasks and sequentially (one after the other). Is there any other better approach?

Thanks
Krishna

**Comment by kumarkrish85** [comment]
@mnadeem Can you please help?

**Comment by mnadeem** [comment]
Can you elaborate more on your requirements?
What is expected, what you  are doing and what is happening ?

**Comment by kumarkrish85** [comment]
I mean I want to run the tasks (IE Test Cases tasks) sequentially and still I want to mark dependency on non-IE Test cases.  for example, if IE-A, IE-B are dependent on TC-C. The graph will be IE-A, TC-C and IE-B, TC-C. Currently, both IE tasks are running in parallel. But I want to run them sequentially even if the thread count is more than one. 

IE Test cases in parallel will give weird results, so selenium advised to run them sequential.

**Comment by mnadeem** [comment]
You have to conditionally build the dexecutor based on browser or maintain two dexecutors

**Comment by kumarkrish85** [comment]
Sure Thanks @mnadeem, I must say the package is really cool. Kudos to your efforts.
