### ISSUE TITLE
Control Task execution order

### ISSUE THREAD

**Issue by kumarkrish85** [dexecutor/dexecutor-core#17]
Hi @mnadeem 

Can you please help me with how do I control the order of task execution. For example, the independent tasks are A, B, and C. In the thread count of 3, I should retain the same order of A, B, and C. But the actual result is sometimes 

- B, A, and C 
- C, B, and A

How do I retain the natural order of A, B, and C. Please help

**Comment by mnadeem** [comment]
Task execution order can't be controlled, you have to drive it based on dependency

**Comment by kumarkrish85** [comment]
@mnadeem, 
Thanks for the update.  Yes, it can't be controlled.
