### ISSUE TITLE
deexecuter example for TableMigration Task

### ISSUE THREAD

**Issue by Raj100782** [dexecutor/dexecutor-core#2]
Hi Nadeem,
          first of all i must say this is very nice work. Thanks for doing this for us.
I have below use case for which I want to use this API
I have text file which contains certain steps to be executed for each table and my txt file as give as below.
1|-1|0|Clear Old data <cleanup.sh>|${LOG_DIR}/{table_name}.log
2|1|0| Create Table <createTable.sh>|${LOG_DIR}/{table_name}.log
3|2|0| Insert into Table <insertIntoTable.sh>|${LOG_DIR}/{table_name}.log

where 
first element is Task 
Second is dependent Task
Third ins Retry
Fourth is actual script<eg. .sh or sql>

I tried modifying the xml (given in one your Migration example )like below

<migration-tasks>
	<task module="Clear Data" taskId="1" version="1.0.2" release="1">
		<task>select * from table1, table3, table4 where xyx= 1;</task>
	</task>

	<task module="Create Data Output Dir" taskId="2" version="1.0.2" release="1">
		<task>select * from table5, table6 where xyx= 1;</task>
	</task>
	<task module="Execute NDW Active Count Check" taskId="3" version="1.0.2" release="1">
		<task>select * from table10, table11 where xyx= 1;</task>
	</task>

	<task module="Execute NDW History Partition Count Check" taskId="4" version="1.0.2" release="2">
		<task>select * from table4, table8 where xyx= 1;</task>
	</task>
	<task module="Execute MELD Active Count Check" taskId="5" version="1.0.2" release="2">
		<task>select * from table8, table9 where xyx= 1;</task>
	</task>

	<task module="Execute MELD History Partition Count Check" taskId="6" version="1.0.2" release="2">
		<task>select * from table10, table19 where xyx= 1;</task>
	</task>
	<task module="Execute Source Count" taskId="7" version="1.0.2" release="2">
		<task>select * from table11, table17 where xyx= 1;</task>
	</task>

	<task module="Check DistCP Completion Status" taskId="8" version="1.0.2" release="3">
		<task>select * from table6, table7 where xyx= 1</task>
	</task>
</migration-tasks>

Could you please help to set dependencies in xml  which matches my requirement.
Let me know If you have any issues regarding the explanation.

Thanks in advance!

Hope to see your response.

**Comment by mnadeem** [comment]
Hi Raj,

you would have to write logic for doing so..
