### ISSUE TITLE
How to generate visual pictures

### ISSUE THREAD

**Issue by B1gB1gRAin** [dexecutor/dexecutor-core#20]
How to generate visual pictures

 DefaultDexecutor<Integer, Integer> executor = newTaskExecutor();
    //Building
    executor.addDependency(1, 2);
    executor.addDependency(2, 3);
    executor.addDependency(3, 4);
    executor.addDependency(4, 5);

**Comment by mnadeem** [comment]
I am not clear on the question, please elaborate

**Comment by B1gB1gRAin** [comment]
`DefaultDexecutor<Integer, Integer> executor = newTaskExecutor();

    executor.addDependency(1, 2);
    executor.addDependency(1, 2);
    executor.addDependency(1, 3);
    executor.addDependency(3, 4);
    executor.addDependency(3, 5);
    executor.addDependency(3, 6);
    
    executor.addDependency(2, 7);
    executor.addDependency(2, 9);
    executor.addDependency(2, 8);
    executor.addDependency(9, 10);
    executor.addDependency(12, 13);
    executor.addDependency(13, 4);
    executor.addDependency(13, 14);
    executor.addIndependent(11);

    executor.execute(new ExecutionConfig().immediateRetrying(2));`


**i  generate the following graph by code.** 

**How can I visualize the  following graph of the above code just like the picture below**
[https://camo.githubusercontent.com/a333fe5c333ff1aa256f91c917b48e465084ebc9/68747470733a2f2f692e706f7374696d672e63632f68764e623731684d2f646578656375746f722d67726170682e706e67](url)

**Comment by B1gB1gRAin** [comment]
**how to generate the following graph by code
![4](https://user-images.githubusercontent.com/18605447/78202980-506fb200-74c8-11ea-972b-b6578326b779.png)
**

**Comment by B1gB1gRAin** [comment]
@mnadeem i am wishing for you.

**Comment by mnadeem** [comment]
You mean how to generate the image from the graph ?

**Comment by B1gB1gRAin** [comment]
> You mean how to generate the image from the graph ?

yes

**Comment by mnadeem** [comment]
I have generated it manually using Power point
