### ISSUE TITLE
Is it possible to interrupt a running task?

### ISSUE THREAD

**Issue by edwardzjl** [dexecutor/dexecutor-core#23]
Is it possible to force interrupt a running task? Given task id or sth.

**Comment by mnadeem** [comment]
What is your use case?

Since we never know when a task start running

**Comment by edwardzjl** [comment]
Our "tasks" refers to executing scripts written in other language (mainly python and perl), which do some analyze jobs, and could take quite long.

We want to interrupt those tasks which took too long and seems to be "dead".

We use ProcessBuilder to execute those scripts, and store the "pid" in our customized "Task".

So if we can get a Task by its id we can get the pid of the process and send the stop signal to it.

**Comment by mnadeem** [comment]
It could be beyond the framework, 

If a task is genuinely taking more time we have provide extra time

If a task is dead, there should be separate process to kill it, however from the framework level we can do the change to have max time a task would take, beyond which we can consider it as dead and continue to other tasks on the flow

**Comment by mnadeem** [comment]
This has been implemented https://github.com/dexecutor/dexecutor-core/issues/25
