### ISSUE TITLE
Spring Support

### ISSUE THREAD

**Issue by fo0** [dexecutor/dexecutor-core#24]
Hi, i am using this lib for long time now and its great!
Thanks for all the hard work to make this possible.

Currently i am working with 
- spring-boot (latest)
- java 1.8 

and trying to get your lib working with spring.
Did you ever used this in spring-boot?

**My Goal --> use inside a Task the spring-context**

I am using the SpringContext (ApplicationContextAware) ([described here](https://confluence.jaytaala.com/display/TKB/Super+simple+approach+to+accessing+Spring+beans+from+non-Spring+managed+classes+and+POJOs)) to access many other content in Unmanaged-Spring-Classes but in the Tasks-Class, where i implement my doings, it doesn't work.

Maybe any ideas? Maybe to add configurable spring-support or workarounds

And again, great lib! thanks!!!

**Comment by mnadeem** [comment]
Great idea, let me think about it

**Comment by fo0** [comment]
I am using your library as a dependency in a seperate library lets call "dex". What I realised now is if I am using your library directly in my main project, than I can access via SpringContext.getBean(...) the spring-context. But if I load your lib indirect via my lib "dex" than its not possible. Any ideas? I am facing out that it could have something to do with compiling. The "dex" lib also has no spring included.

**Comment by mnadeem** [comment]
Following would be helpful

https://github.com/dexecutor/dexecutor-spring-example

**Comment by fo0** [comment]
this is great, thanks a lot
