### ISSUE TITLE
How to stop the task or the entire graph from executing?

### ISSUE THREAD

**Issue by xiaomao23zhi** [dexecutor/dexecutor-core#27]
Hi,
I'm trying to use Dexeutor as a workflow engine in my Sping project. Basically I'm using Restful API to controll the workflow. When the workflow is submitted and running, I need to stop it from running manully.
ex:
```
public class WorkFlowManager {
	...
	private void buildGraph(String workflowId) {
		// build graph;
	}

	public void execute(String workflowId) {
                buildGraph(workflowId);
		this.dexecutor.execute(ExecutionConfig.TERMINATING);
	}

	public void stop(String workflowId) {
                // **how do I do this?**
        }
}
```
Controllers:
```
public class WorkflowController {
	final WorkflowManager workflowManager;

	public void execute(String workflowId) {
		return workflowManager.execute(workflowId);
	}

	// **How to do this?**
	public void kill(String workflowId) {
		return workflowManager.stop(workflowId);
	}
```

**Comment by mnadeem** [comment]
1.  Add time out : https://github.com/dexecutor/dexecutor-core/wiki/How-Do-I-%3F#timeout-support Or from Task execution throw exception
2.  Terminating behavior : ExecutionConfig.TERMINATING

What exactly is your use case?

**Comment by xiaomao23zhi** [comment]
Taking the same example of the #25
```
```

**Comment by xiaomao23zhi** [comment]
Taking the same example of issue #25
```
         A
      /  |   \
    B    C    D
    |
    E
```
Let's say task A is finished, task B/C/D is running and task E is pending. How to stop current running tasks (set task B/C/D FAILED or SKIPPED)?

It's somethingI like Future.cancel(...) you mentioned in the How-Do-I, but I couldn't find where and how to invoke Future.cancel().

**Comment by xiaomao23zhi** [comment]
> from Task execution throw exception

Thank you for this advice. I've found a solution. I persist all tasks to database, so when I want to stop current running tasks, I change theses tasks states to "KILLED", then I throw a TaskExecutionException within the execute() method. And combining with ExecutionConfig.TERMINATING setup, the whole graph can be stopped.

So in my use case I kinda need to access DefaultDexectuor asynchronously, I'm thinking how about persist DefaultDexecutor instances, so it can be reacquired later on thus to do some workflow controll like:
```
DefaultDexectuor executor = DefaultDexectuor.getDexecutor(instanceId);
// Stop all Running tasks
executor.stopAllRunningTasks();
// Stop one task
executor.stopTask(id);
// Peek ExecutionResults
ExecutionResults<> results = executor.getExecutionResult();
// Get state
DexecutorState<> state = executor.getConfig().getDexecutorState();
```
