### ISSUE TITLE
How to specify a taskId to start with programmatically?

### ISSUE THREAD

**Issue by xiaomao23zhi** [dexecutor/dexecutor-core#28]
Task graph example:
```
         A
      /  |   \
    B    C    D
    |
    E
```
In my use case, I have several scenarioes, for example, in scenario 1 is to execute from task A, while in scenario 2, I can specify executor to start with task B, so only task B and task E will be executed.
So how do I do this?
I'm thinking about something like this:
```
public void runDexecutor(int scenario) {
	LOGGER.debug("Running..");
	DefaultDexecutor<Integer, Integer> executor = newDexecutor();
	addDependency(executor);

	if (scenario == 1) {
		executor.execute(ExecutionConfig.NON_TERMINATING);
	}
	if (scenario == 2) {
		// How to do this?
		executor.execute(ExecutionConfig.NON_TERMINATING, taskIdToStartWith);
	}
}
```

**Comment by mnadeem** [comment]
You can add that logic in task itself to skip : https://github.com/dexecutor/dexecutor-core/wiki/How-Do-I-%3F#how-do-i-execute-tasks-conditionally-based-on-the-result-of-parent-tasks

**Comment by mnadeem** [comment]
That would be error prone, as there could be multiple starts, here is an example, in this case 1, 11 and 12 are starts

![image](https://user-images.githubusercontent.com/476145/118989183-73487880-b99f-11eb-99bb-cdd6d3d58248.png)

Here is how you can do it 

    private static class SleepyTaskProvider implements TaskProvider<String, String> {

    public Task<String, String> provideTask(final String id) {

       if   ( (scenario == 1 ||  scenario == 5) && "A".equals(id)) {
          return new EmptyTask();
       } else {

        return new Task<String, String>() {

            @Override
            public String execute() {
                try {
                    //Perform some task
                    Thread.sleep(500);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                String result = id + "processed";
                return result;
            }

            @Override
            public boolean shouldExecute(ExecutionResults<String, String> parentResults) {
                ExecutionResult<String, String> firstParentResult = parentResults.getFirst();
                //Do some logic with parent result
                if ("B".equals(id) && firstParentResult.isSkipped() && firstParentResult.getResult() == "No") {
                    return false;
                }
                return true;
            }
        };          
    }

    }

**Comment by mnadeem** [comment]
Closing this ticket for now
