### ISSUE TITLE
Support for persitence, pause / resume executions

### ISSUE THREAD

**Issue by seseso** [dexecutor/dexecutor-core#29]
What would be the best way to incorporate the following requirements:

- Support for pause / resume executions (async) - Receive a "Pause" command for an execution should finish running tasks but not trigger next tasks, until a "Resume" command is issued
- How could this model be persisted, thinking, for instance, on a Stop / Start of the JVM or the previously refered Pause / resume? I'm thinking on some logic, maybe on Listener...
- Both of previous scenarios in a Distributed context

Thanks in advance!

**Comment by mnadeem** [comment]
Thanks for opening this ticket

Above two can be done using distributed execution, Work was started on Distributed execution : https://github.com/dexecutor/dexecutor-core/wiki/Distributed-Execution

However since there not much demand, it is stopped for now.

https://reachmnadeem.wordpress.com/2016/10/08/multi-node-distributed-execution-using-ignite-and-dexecutor/

**Comment by mnadeem** [comment]
It can achieved in non-distributed mode as well, you just have to  implement com.github.dexecutor.core.DexecutorState<T, R>

You can store the info in DB, In memory grid, file etc.

**Comment by mnadeem** [comment]
What is your business use case ?

**Comment by mnadeem** [comment]
This commit add example for pause/resume

https://github.com/dexecutor/dexecutor-core/commit/00be168979cfad04e32f446d6915ec24a6af5dc8

This example shows an example how to pause and recover : https://github.com/dexecutor/dexecutor-core/blob/master/src/test/java/com/github/dexecutor/core/DexecutorPauseAndRecover.java


Would be release soon

**Comment by mnadeem** [comment]
Further on persistence you can serialize/deserialize  com.github.dexecutor.core.DexecutorState as one of the simplest mechanisms.

**Comment by mnadeem** [comment]
2.1.4 released with the fixes

**Comment by seseso** [comment]
Thanks for the quick reply!
My use case: I have a bunch of tasks (some long running ones) which I need to orchestrate with some rules (sequentially / parallel) in a form of flows. The user must be able to "monitor" the execution, including pause / resume. I also need to have a "disaster recovery" plan for existing running flows (for instance, when a server restart occurs).
I already have this implemented, but, at the moment, it only works on a single node and does not support distributed executions. I would like to migrate do dexecutor for that reason and I'm accessing what would be the best route and least risky path for that.
BTW, do you have any plans to upgrade the various sub-projects regarding distributed executions? I've tried Ignite (which I dumped since it doesn't work weel with Java 11) and Infinispan but the versions used (dexecutor and Infinispan for that matter) are a little bit outdated. Also, I would like to try an event driven approach (with AMQP / JMS) for the distribution part since that would fit more cleanly in our architecture.

**Comment by tantou** [comment]
> Further on persistence you can serialize/deserialize com.github.dexecutor.core.DexecutorState as one of the simplest mechanisms.

Can you show the code how to do persistence?

**Comment by mnadeem** [comment]
Underlying execution engine serializes / deserilizes

https://reachmnadeem.wordpress.com/2016/09/10/multi-node-distributed-execution-using-infinispan-and-dexecutor/
https://reachmnadeem.wordpress.com/2016/10/08/multi-node-distributed-execution-using-ignite-and-dexecutor/
https://reachmnadeem.wordpress.com/2016/10/11/multi-node-distributed-execution-using-hazelcast-and-dexecutor/



https://github.com/dexecutor/dexecutor-ignite/blob/master/src/main/java/com/github/dexecutor/ignite/IgniteDexecutorState.java

https://github.com/dexecutor/dexecutor-infinispan/blob/master/src/main/java/com/github/dexecutor/infinispan/InfinispanExecutionEngine.java
