### ISSUE TITLE
Question on Task's ID type

### ISSUE THREAD

**Issue by nsturr** [dexecutor/dexecutor-core#5]
This is not really an issue but a question. The requirement for the Task's ID (T) is that is implements Comparable. Why? There is nothing that calls the API compareTo (the only requirement for Comparable) and nothing the T is used by requires it that I could see. Was this a prior implementation when the ID was used for comparison order?

**Comment by mnadeem** [comment]
I don't remember the reason for this, however seems like a good suggestion
