### ISSUE TITLE
How to feed the response of one task to other task?

### ISSUE THREAD

**Issue by Aditya9271** [dexecutor/dexecutor-core#8]
Let say there are two tasks A, B.
A vends d as response and which is taken by B as its input field, can you provide an example by which we can achieve that, apologies if i missed something here.

**Comment by mnadeem** [comment]
Following should help you

https://github.com/dexecutor/dexecutor-core/wiki/How-Do-I-%3F

**Comment by adit2ism** [comment]
hey Nadeem, above link points out whether the dependent task should be executed on the basis of result of parent task, what i wanted to know whether if i can access the result of parent task while the execution of child task,  so here,

public Task<String, String> provideTask(final String id) {

        return new Task<String, String>() {

            @Override
            public String execute() {
                try {
                    //Perform some task
                    Thread.sleep(500);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                String result = id + "processed";
                return result;
            }

            @Override
            public boolean shouldExecute(ExecutionResults<String, String> parentResults) {
                ExecutionResult<String, String> firstParentResult = parentResults.getFirst();
                //Do some logic with parent result
                if ("B".equals(id) && firstParentResult.isSkipped() && firstParentResult.getResult() == "No") {
                    return false;
                }
                return true;
            }
        };          
    }

i can access the parentResult only in shouldExecute method, but can't in execute method, is there any method through which we can access the parentResult, if not have you considered adding that?

**Comment by mnadeem** [comment]
let me think about.....

Mean while appreciate if you could describe your usecase, that would help me implement it in a better way..

meaning why you would like to access parent result while executing?

**Comment by adit2ism** [comment]
We have a use case where we want to fetch the details of an employee which will be vended by GetEmployeeDetails API, however GetEmployeeDetails API only accepts employeeId as an input.

For fetching employeeId we call a different GetCompany API passing companyName as input.

Both of the APIs are of different downstream services.

As you can see, we have a dependency between both of them,  i wanted to fetch the response of GetCompany API to get employeeId to call GetEmployeeDetails API.

**Comment by mnadeem** [comment]
By when you want this ?

**Comment by adit2ism** [comment]
We have an important feature to launch by the end of December, it would be good to have this by mid week of December. If you can add this feature by that time that would be great.

**Comment by adit2ism** [comment]
We are creating a REST API, but i won't be able to disclose any further information.

**Comment by mnadeem** [comment]
Committed the change to get getParentResults anytime.

from task you just have to call getParentResults()

**Comment by mnadeem** [comment]
<dependency>
  <groupId>com.github.dexecutor</groupId>
  <artifactId>dexecutor-core</artifactId>
  <version>2.1.0</version>
</dependency>
